ocre-tests: handle test group failure gracefully
Signed-off-by: Patrick Robb <probb@iol.unh.edu>

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -22,7 +22,12 @@ jobs:
       
             - name: Flash Validation Tests
               run: |
-                  cd tests && bash beginTests.sh "flashValidation"
+                cd tests && bash beginTests.sh "flashValidation"
+                EXIT_CODE=$?
+                if [ $EXIT_CODE -ne 0 ]; then
+                  echo "TEST FAILURE: flashValidation test group failed."
+                fi
+                exit $EXIT_CODE
 
             - name: Print Flash Validation Logs
               if: always()
